---
abstract: 'Tapper - Message receiver for Tapper MCP'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IO::Socket::INET: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-MCP-MessageReceiver
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  App::Daemon: 0
  EV: 0
  Moose: 1.24
  Tapper::Base: 3.000010
  Tapper::Config: 3.000010
  Tapper::Model: 3.000010
  YAML::Syck: 1.17
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-MCP-MessageReceiver
  license: http://dev.perl.org/licenses/
  repository: git://github.com/amd/Tapper-MCP-MessageReceiver.git
version: 3.000010
